### ISSUE TITLE
Please add the airport EDNK

### ISSUE THREAD

**Issue by florianjb** [glidernet/ogn-live#60]
Hello,

can you please add the airport EDNK (Kirchdorf/Inn) to the airport list?
http://flightlog.glidernet.org/index.php?a=EDNK&s=QFE&u=m&z=0&p=&d=13042017&j=1

Best regards
Florian

**Comment by florianjb** [comment]
(l.lat BETWEEN 48.2353 AND 48.2417) AND (l.lon BETWEEN 12.9720 AND 12.9821)

**Comment by 6200puej** [comment]
Good eveningI have not rights to do this. You must contact the administrator.
Regarda


Von Samsung-Tablet gesendet
-------- Ursprüngliche Nachricht --------Von: florianjb <notifications@github.com> Datum: 27.04.17  07:59  (GMT+01:00) An: glidernet/ogn-live <ogn-live@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Betreff: Re: [glidernet/ogn-live] Please add the airport EDNK (#60) 
(l.lat BETWEEN 48.2353 AND 48.2417) AND (l.lon BETWEEN 12.9720 AND 12.9821)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/glidernet/ogn-live","title":"glidernet/ogn-live","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/glidernet/ogn-live"}},"updates":{"snippets":[{"icon":"PERSON","message":"@florianjb in #60: (l.lat BETWEEN 48.2353 AND 48.2417) AND (l.lon BETWEEN 12.9720 AND 12.9821)"}],"action":{"name":"View Issue","url":"https://github.com/glidernet/ogn-live/issues/60#issuecomment-297619624"}}}
